ALTER SESSION SET "_ORACLE_SCRIPT" = TRUE;

-- Creación del esquema REGISTRO_VISITANTES
CREATE USER REGISTRO_VISITANTES IDENTIFIED BY 1234;
GRANT DBA TO REGISTRO_VISITANTES;

-- Crear la tabla MENU_ITEM
CREATE TABLE REGISTRO_VISITANTES.MENU_ITEM 
(
    ID NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(200) NOT NULL,
    URL VARCHAR2(4000) NOT NULL,
    PADRE_ID NUMBER,
    CONSTRAINT FK_MENU_ITEM_PADRE FOREIGN KEY (PADRE_ID) REFERENCES REGISTRO_VISITANTES.MENU_ITEM(ID)
);

-- Secuencia para la tabla MENU_ITEM
CREATE SEQUENCE MENU_ITEM_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Trigger para la secuencia de MENU_ITEM
CREATE OR REPLACE TRIGGER AL_INSERTAR_MENU_ITEM BEFORE INSERT ON REGISTRO_VISITANTES.MENU_ITEM FOR EACH ROW
BEGIN
    SELECT MENU_ITEM_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

-- Crear la tabla VISITANTES
CREATE TABLE REGISTRO_VISITANTES.VISITANTES
(
    ID NUMBER PRIMARY KEY,
    DUI VARCHAR(9) NOT NULL,
    NOMBRE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(200) UNIQUE NOT NULL,
    FECHA_NACIMIENTO DATE NOT NULL,
    TELEFONO VARCHAR(20) NOT NULL,
    GENERACION VARCHAR(100)
);

-- Secuencia para la tabla VISITANTES
CREATE SEQUENCE VISITANTES_SEQ START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

-- Trigger para la secuencia de VISITANTES
CREATE OR REPLACE TRIGGER AL_INSERTAR_VISITANTE BEFORE INSERT ON REGISTRO_VISITANTES.VISITANTES FOR EACH ROW
BEGIN
    SELECT MENU_ITEM_SEQ.NEXTVAL INTO :NEW.ID FROM DUAL;
END;

COMMIT;